import type { NextPage } from "next";
import Head from "next/head";
import tw from "twin.macro";

const Input = tw.input`
rounded-md
border-gray-300
shadow-sm
focus:border-indigo-500
focus:ring-indigo-500 sm:text-sm
`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Input type="text" />
      </main>
    </div>
  );
};

export default Home;
